# Configurações de Crews do Sistema

# Crew de Pesquisa Básica
research_crew:
  name: "Crew de Pesquisa"
  description: "Crew especializada em pesquisa e coleta de informações"
  agents: ["researcher", "analyst"]
  tasks: ["research_task", "analysis_task"]
  verbose: true
  memory: true

# Crew de Conteúdo
content_crew:
  name: "Crew de Conteúdo"
  description: "Crew especializada em criação e revisão de conteúdo"
  agents: ["writer", "reviewer"]
  tasks: ["writing_task", "review_task"]
  verbose: true
  memory: true

# Crew de Análise de Planilhas
excel_crew:
  name: "Crew de Análise de Planilhas"
  description: "Crew especializada em análise e comparação de planilhas Excel"
  agents: ["excel_analyst", "analyst"]
  tasks: ["excel_analysis_task", "analysis_task"]
  verbose: true
  memory: true

# Crew do WhatsApp
whatsapp_crew:
  name: "Crew do WhatsApp"
  description: "Crew especializada em monitorar grupos do WhatsApp e baixar arquivos"
  agents: ["whatsapp_monitor", "file_downloader", "file_organizer"]
  tasks: ["whatsapp_monitoring_task", "file_download_task", "file_organization_task"]
  verbose: true
  memory: true
  parameters:
    whatsapp_monitoring_task:
      group_name: "Grupo de Trabalho"
      max_messages: 100
    file_download_task:
      output_path: "./downloads/whatsapp"
    file_organization_task:
      base_path: "./downloads/whatsapp"

# Crew Completa
full_crew:
  name: "Crew Completa"
  description: "Crew com todos os agentes para tarefas complexas"
  agents: ["researcher", "analyst", "writer", "reviewer", "coordinator"]
  tasks: ["research_task", "analysis_task", "writing_task", "review_task", "coordination_task"]
  verbose: true
  memory: true 