research_task:
  description: "Realizar pesquisa detalhada sobre {topic}"
  expected_output: "Relatório completo com informações coletadas, fontes e dados relevantes"
  agent: "researcher"
  context: ["Pesquisa inicial para coleta de informações"]

analysis_task:
  description: "Analisar dados coletados sobre {topic} e gerar insights"
  expected_output: "Análise estruturada com insights, tendências e recomendações"
  agent: "analyst"
  context: ["Análise dos dados pesquisados"]

writing_task:
  description: "Criar conteúdo baseado na pesquisa e análise sobre {topic}"
  expected_output: "Conteúdo bem estruturado, claro e informativo"
  agent: "writer"
  context: ["Criação de conteúdo baseado em dados"]

review_task:
  description: "Revisar e validar o conteúdo criado sobre {topic}"
  expected_output: "Conteúdo revisado e validado com sugestões de melhoria"
  agent: "reviewer"
  context: ["Revisão de qualidade do conteúdo"]

coordination_task:
  description: "Coordenar o fluxo de trabalho entre os agentes para {topic}"
  expected_output: "Plano de execução coordenado e cronograma de entregas"
  agent: "coordinator"
  context: ["Coordenação geral do projeto"]

excel_analysis_task:
  description: "Analisar dados de planilhas Excel relacionadas a {topic}"
  expected_output: "Relatório de análise de dados com comparações e insights"
  agent: "excel_analyst"
  context: ["Análise específica de dados em planilhas"]

whatsapp_monitoring_task:
  description: "Monitorar grupo do WhatsApp '{group_name}' em busca de mensagens com arquivos e links de serviços em nuvem"
  expected_output: "Lista de mensagens encontradas com arquivos e links identificados, incluindo timestamps"
  agent: "whatsapp_monitor"
  context: ["Monitoramento contínuo do grupo do WhatsApp"]

file_download_task:
  description: "Baixar arquivos identificados das mensagens do WhatsApp e links de serviços em nuvem"
  expected_output: "Arquivos baixados com sucesso e relatório de downloads realizados"
  agent: "file_downloader"
  context: ["Download de arquivos de múltiplas fontes"]

file_organization_task:
  description: "Organizar arquivos baixados, adicionar timestamps aos nomes e criar estrutura de pastas organizada"
  expected_output: "Arquivos organizados com nomes padronizados incluindo data e hora, estrutura de pastas criada"
  agent: "file_organizer"
  context: ["Organização e padronização de arquivos"] 