read_excel_column:
  name: Ler Coluna Excel
  description: Lê uma coluna específica de um arquivo Excel e retorna os dados como
    lista
  category: Excel
  parameters:
    file_path: Caminho do arquivo Excel
    column_name: Nome da coluna a ser lida
  returns: Lista com os dados da coluna
  example: read_excel_column('dados.xlsx', 'Material')
read_excel_file:
  name: Ler Arquivo Excel
  description: Lê um arquivo Excel completo e retorna informações estruturadas sobre
    sua estrutura
  category: Excel
  parameters:
    file_path: Caminho do arquivo Excel
  returns: Dicionário com informações do arquivo (colunas, linhas, tipos de dados,
    etc.)
  example: read_excel_file('dados.xlsx')
compare_text_similarity:
  name: Comparar Similaridade de Texto
  description: Compara a similaridade entre duas listas de textos usando algoritmos
    fuzzy matching
  category: Análise
  parameters:
    list1: Primeira lista de textos
    list2: Segunda lista de textos
  returns: Dicionário com correspondências e scores de similaridade
  example: compare_text_similarity(['cimento', 'areia'], ['cimento portland', 'areia
    média'])
analyze_excel_similarity:
  name: Análise de Similaridade Excel
  description: Realiza análise completa de similaridade entre duas planilhas Excel
  category: Excel
  parameters:
    file1_path: Caminho do primeiro arquivo Excel
    file2_path: Caminho do segundo arquivo Excel
    column1: Nome da coluna no primeiro arquivo
    column2: Nome da coluna no segundo arquivo
  returns: Análise completa com estatísticas e recomendações
  example: analyze_excel_similarity('orcamento1.xlsx', 'orcamento2.xlsx', 'Material',
    'Descrição')
detect_data_patterns:
  name: Detectar Padrões nos Dados
  description: Analisa uma coluna de dados e detecta padrões, tipos de dados e características
  category: Análise
  parameters:
    file_path: Caminho do arquivo Excel
    column_name: Nome da coluna a ser analisada
  returns: Dicionário com padrões detectados nos dados
  example: detect_data_patterns('dados.xlsx', 'Preço')
generate_excel_report:
  name: Gerar Relatório Excel
  description: Gera um relatório estruturado baseado nos resultados de análise
  category: Relatórios
  parameters:
    analysis_results: Resultados da análise (dicionário)
  returns: Relatório formatado em texto
  example: generate_excel_report(resultados_analise)
validate_excel_file:
  name: Validar Arquivo Excel
  description: Valida um arquivo Excel e retorna informações sobre sua estrutura e
    qualidade
  category: Excel
  parameters:
    file_path: Caminho do arquivo Excel
  returns: Dicionário com informações de validação
  example: validate_excel_file('dados.xlsx')
whatsapp_connect:
  name: Conectar ao WhatsApp
  description: Estabelece conexão com o WhatsApp Web para monitoramento de grupos
  category: WhatsApp
  parameters:
    session_name: Nome da sessão do WhatsApp
  returns: Status da conexão
  example: whatsapp_connect('minha_sessao')
whatsapp_get_messages:
  name: Obter Mensagens do WhatsApp
  description: Obtém mensagens de um grupo específico do WhatsApp
  category: WhatsApp
  parameters:
    group_name: Nome do grupo do WhatsApp
    limit: Número máximo de mensagens a obter
  returns: Lista de mensagens com metadados
  example: whatsapp_get_messages('Grupo de Trabalho', 100)
extract_cloud_links:
  name: Extrair Links de Nuvem
  description: Extrai links de serviços em nuvem (Google Drive, OneDrive, Dropbox) de mensagens
  category: WhatsApp
  parameters:
    messages: Lista de mensagens do WhatsApp
  returns: Lista de links de serviços em nuvem encontrados
  example: extract_cloud_links(mensagens_grupo)
download_cloud_file:
  name: Baixar Arquivo da Nuvem
  description: Baixa arquivo de serviços em nuvem (Google Drive, OneDrive, Dropbox)
  category: Download
  parameters:
    cloud_link: Link do arquivo na nuvem
    output_path: Caminho onde salvar o arquivo
  returns: Status do download e caminho do arquivo
  example: download_cloud_file('https://drive.google.com/file/d/123', './downloads/')
download_whatsapp_file:
  name: Baixar Arquivo do WhatsApp
  description: Baixa arquivo anexado a uma mensagem do WhatsApp
  category: Download
  parameters:
    message: Mensagem do WhatsApp com arquivo
    output_path: Caminho onde salvar o arquivo
  returns: Status do download e caminho do arquivo
  example: download_whatsapp_file(mensagem_com_arquivo, './downloads/')
rename_file_with_timestamp:
  name: Renomear Arquivo com Timestamp
  description: Adiciona timestamp (data e hora) ao nome do arquivo
  category: Organização
  parameters:
    file_path: Caminho do arquivo original
    timestamp: Timestamp da mensagem (datetime)
  returns: Caminho do arquivo renomeado
  example: rename_file_with_timestamp('./arquivo.pdf', '2024-01-15 14:30:00')
organize_files_by_date:
  name: Organizar Arquivos por Data
  description: Organiza arquivos em pastas por data de download
  category: Organização
  parameters:
    files_list: Lista de arquivos baixados
    base_path: Caminho base para organização
  returns: Estrutura de pastas criada
  example: organize_files_by_date(arquivos_baixados, './downloads/')
